### PR TITLE
Import abseil-cpp source tag 20230802.0

### PR DESCRIPTION
**Pull request by HannahShiSFB**
Resubmit #17

@paulb777 Can you help trigger the CI on this PR?
I manually ran the commands in `spm.yml`, they all succeeded.

### CODE REVIEW

**Comment by paulb777** [comment]
@HannahShiSFB CI should now automatically run on any PR. It had been disabled because of no activity on the repo for 90 days.  

Looks like it's failing ...

**Comment by HannahShiSFB** [comment]
Yeah, same redundant module import error, looking...

**Comment by HannahShiSFB** [comment]
Looks like we need to ignore the include warning for it to work, previous patch #9

**Review by paulb777 — APPROVED** [review]
LGTM, thanks!

We may want to merge #21 to support the current version with a privacy manifest and keep the commit history linear.

cc: @ncooke3

**Comment by ncooke3** [comment]
> We may want to merge #21 to support the current version with a privacy manifest and keep the commit history linear.

#21 LGTM–– thanks @HannahShiSFB.

@paulb777, should I go ahead and merge #21 before this PR merges, then?

**Comment by paulb777** [comment]
Probably. Let's sync on the tagging strategy when we meet today.

**Comment by paulb777** [comment]
Merged and published a 0.20230802.0 tag

**Pull request merged**
