### PR TITLE
Upgrade to abseil-cpp 20240722.0

### PR DESCRIPTION
**Pull request by HannahShiSFB**
Abseil-cpp source snapshot from release tag [20240722.0](https://github.com/abseil/abseil-cpp/releases/tag/20240722.0)

Removed all test and benchmark files:

```
rm -rf `find absl/ -name "*_test.cc"`
rm -rf `find absl/ -name "*_benchmark.cc"`
rm absl/status/internal/status_matchers.*
rm -rf absl/time/internal/cctz/testdata
rm -rf `find absl/ -name "BUILD.bazel"`
rm -rf `find absl/ -name "CMakeLists.txt"`
rm -rf absl/copts
```

For gRPC dependency starting form 1.68.x https://github.com/grpc/grpc/pull/37543

### CODE REVIEW

**Comment by HannahShiSFB** [comment]
CC: @paulb777 @sampajano

**Review by paulb777 — COMMENTED** [review]
Is it feasible to remove the files necessary to fix the 600+ build warnings?  https://github.com/firebase/abseil-cpp-SwiftPM/actions/runs/11714366860/job/32628923274#step:6:817

**Comment by HannahShiSFB** [comment]
Majority of them are timezon data, which I don't know whether it's safe to remove them.
There are also some inc files cannot be removed.
I can remove the bazel and cmake build files.

**Comment by paulb777** [comment]
If SPM isn't finding the timezone data, they're not being built. If they're needed, they should be included in a `resources` specification in the Package.swift.

**Review by paulb777 — APPROVED** [review]
LGTM Thanks!

Is it ready to merge and tag?

**Comment by HannahShiSFB** [comment]
Yes, please go ahead, thanks.

**Comment by paulb777** [comment]
Merged, tagged, and created a GitHub release - https://github.com/firebase/abseil-cpp-SwiftPM/releases/tag/0.20240722.0

**Pull request merged**
